apiVersion: v1
kind: Pod
metadata:
  name: nginxapp 
  labels:
    name: nginxapp 
spec:
  containers:
  - name: nginxapp 
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
