apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployapp
  template:
    metadata:
      labels:
        app: deployapp
    spec:
      containers:
      - name: nginxapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
