apiVersion: v1
kind: Service
metadata:
  name: nginxnode
spec:
  type: NodePort
  selector:
    name: nginxapp # selector về Pod có lable name=nginxapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
