apiVersion: v1
kind: Service
metadata:
  name: headless       # đặt tên Service
spec:
  clusterIP: None      # Thiết lập là Headless Svc
  selector:
    name: nginxapp # selector về Pod có lable name=nginxapp
  ports:
    - protocol: TCP
      port: 80         # Cổng Service
      targetPort: 80   # Cổng POD (container, endpoints)